In [72]:
i = 10

In [73]:
a = 5

In [74]:
a * i

50

In [75]:
a * a

25

In [76]:
i = 7

In [77]:
a * i

35

In [78]:
x = 10

In [79]:
X = 5

In [80]:
print(x)

10


In [81]:
print(X)

5


In [82]:
x*X

50

In [83]:
x = 0

In [84]:
x*x + 3*x + 40

40

In [85]:
x = 5

In [86]:
x*x + 3*x + 40

80

In [87]:
import numpy as np
## SHIFT+ENTER

In [88]:
a = np.array([1.0,2.0,3])

In [89]:
a

array([1., 2., 3.])

In [90]:
type(a)

numpy.ndarray

In [91]:
a.dtype

dtype('float64')

In [92]:
a.ndim

1

In [93]:
a = np.arange(15).reshape(3, 5)

In [94]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
a.ndim

2

In [96]:
a.size

15

In [97]:
a.shape

(3, 5)

In [98]:
a.dtype

dtype('int64')

In [99]:
a.itemsize

8

In [100]:
b = np.array(['xyz','wery'])

In [101]:
b

array(['xyz', 'wery'], dtype='<U4')

In [102]:
b.dtype

dtype('<U4')

In [103]:
b.dtype.name

'str128'

In [104]:
c = np.array([1,2,3], dtype=complex)

In [105]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [106]:
c.dtype

dtype('complex128')

In [107]:
c.dtype.name

'complex128'

In [108]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [109]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
d = np.ones((4,4))

In [113]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [114]:
d.dtype

dtype('float64')

In [115]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
x = np.arange(0,10,0.2)

In [119]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [120]:
x.dtype

dtype('float64')

In [121]:
x = np.arange(0,10)

In [122]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [124]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [125]:
y = x + 5

In [126]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [128]:
z = x+y

In [129]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [130]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [131]:
z = x + np.sqrt(y)

In [132]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [133]:
sqrt(x)

NameError: name 'sqrt' is not defined

In [ ]:
np.sqrt(x)

In [ ]:
a.sum()

In [ ]:
x.sum()

In [ ]:
x.min()

In [ ]:
np.sin(x)

In [ ]:
# x =+ 1

In [134]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
x += 1

In [138]:
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [140]:
x.std()

2.8722813232690143

In [141]:
x.mean()

7.5

In [142]:
x.max()

12

In [143]:
a = np.arange(10,15)

In [144]:
a

array([10, 11, 12, 13, 14])

In [145]:
a[0]

10

In [146]:
a[-1]

14

In [147]:
a[-2]

13

In [148]:
a[-5]

10

In [150]:
a = np.arange(9).reshape(3,3)

In [151]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
a[1,2]

5

In [153]:
a[1]

array([3, 4, 5])

In [154]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
a.arange(16)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [156]:
a = np.arange(16)

In [157]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [158]:
a = np.arange(99)

In [159]:
a[22:33]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [160]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [161]:
a +=1


In [162]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [163]:
a[22:33]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [164]:
a[[11]]

array([12])

In [166]:
a[1:10:3]

array([2, 5, 8])

In [167]:
a[22:88:1]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [168]:
a[22:88:2]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55,
       57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87])

In [169]:
a[88:22:-2]

array([89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67, 65, 63, 61, 59, 57,
       55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25])

In [170]:
a[88:22:1]

array([], dtype=int64)

In [171]:
a[::10]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [173]:
a = np.arange(0,9).reshape(3,3)

In [174]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
a[:,0]

array([0, 3, 6])

In [176]:
a[0,:]

array([0, 1, 2])

In [177]:
a[-1,-1]

8

In [178]:
a[:-1,:-1]

array([[0, 1],
       [3, 4]])

In [179]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [180]:
a[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [181]:
a[:-1:,:-1:]

array([[0, 1],
       [3, 4]])

In [182]:
a[:,0]

array([0, 3, 6])

In [183]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [194]:
a[[0,2],0:3]

array([[0, 1, 2],
       [6, 7, 8]])

In [187]:
for i in a:
    print (i)

[0 1 2]
[3 4 5]
[6 7 8]


In [196]:
a[[0,2],]

array([[0, 1, 2],
       [6, 7, 8]])

In [198]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
