In [3]:
import numpy as np
a = np.arange(0,9).reshape(3,3)

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.apply_along_axis(np.mean, axis = 0, arr = a)

array([3., 4., 5.])

In [7]:
np.apply_along_axis(np.mean, axis = 1, arr = a)

array([1., 4., 7.])

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
def halfofValue(x):
    return x/2

In [10]:
np.apply_along_axis(halfofValue, axis = 0, arr = a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [11]:
np.apply_along_axis(halfofValue, axis = 1, arr = a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
def myFunc(x):
    return x-1

In [13]:
np.apply_along_axis(myFunc, axis = 0, arr = a)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [14]:
np.apply_along_axis(myFunc, axis = 1, arr = a)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [16]:
a = np.random.random((3,3))

In [17]:
a

array([[0.6880775 , 0.4110019 , 0.73778537],
       [0.88839858, 0.0102453 , 0.56436919],
       [0.94330439, 0.23533948, 0.20579285]])

In [18]:
a < 0.5

array([[False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [20]:
b = a > 0.5

In [21]:
b

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False, False]])

In [22]:
b.dtype

dtype('bool')

In [27]:
b = a[a<0.5]

In [28]:
b

array([[0.4110019 , 0.0102453 ],
       [0.23533948, 0.20579285]])

In [25]:
b = a[a == 0.5]

In [26]:
b

array([], dtype=float64)

In [30]:
a

array([[0.6880775 , 0.4110019 , 0.73778537],
       [0.88839858, 0.0102453 , 0.56436919],
       [0.94330439, 0.23533948, 0.20579285]])

In [31]:
a = np.random.random(12)

In [32]:
a

array([0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
       0.96447594, 0.66099933, 0.42521513, 0.2267215 , 0.630264  ,
       0.68707791, 0.06289988])

In [33]:
a.reshape(3,4)

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [34]:
a.shape

(12,)

In [36]:
a.shape = (2,6)

In [37]:
a

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
        0.96447594],
       [0.66099933, 0.42521513, 0.2267215 , 0.630264  , 0.68707791,
        0.06289988]])

In [38]:
a.reshape(3,4)

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [39]:
a

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
        0.96447594],
       [0.66099933, 0.42521513, 0.2267215 , 0.630264  , 0.68707791,
        0.06289988]])

In [40]:
a.ravel()

array([0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
       0.96447594, 0.66099933, 0.42521513, 0.2267215 , 0.630264  ,
       0.68707791, 0.06289988])

In [41]:
a.shape

(2, 6)

In [42]:
a

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
        0.96447594],
       [0.66099933, 0.42521513, 0.2267215 , 0.630264  , 0.68707791,
        0.06289988]])

In [43]:
b = a


In [44]:
b.shape = (12)

In [45]:
b

array([0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
       0.96447594, 0.66099933, 0.42521513, 0.2267215 , 0.630264  ,
       0.68707791, 0.06289988])

In [46]:
a

array([0.71141604, 0.4200857 , 0.54073917, 0.45049048, 0.64082878,
       0.96447594, 0.66099933, 0.42521513, 0.2267215 , 0.630264  ,
       0.68707791, 0.06289988])

In [47]:
b.shape = (3,4)

In [48]:
a

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [52]:
# b and a are pointing to the same object so, a and b both are changed
b

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [51]:
a.transpose()

array([[0.71141604, 0.64082878, 0.2267215 ],
       [0.4200857 , 0.96447594, 0.630264  ],
       [0.54073917, 0.66099933, 0.68707791],
       [0.45049048, 0.42521513, 0.06289988]])

In [53]:
b

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [54]:
a

array([[0.71141604, 0.4200857 , 0.54073917, 0.45049048],
       [0.64082878, 0.96447594, 0.66099933, 0.42521513],
       [0.2267215 , 0.630264  , 0.68707791, 0.06289988]])

In [56]:
a = np.ones((3,3))

In [57]:
b = np.zeros((3,3))

In [59]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [61]:
a = np.arange(16).reshape(4,4)

In [62]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
[x, y] = np.hsplit(a,2)

In [69]:
x.shape

(4, 2)

In [71]:
y.shape

(4, 2)

In [81]:
a.shape

(4, 4)

In [78]:
[x, y] = np.vsplit(a,2)

In [79]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [83]:
b = a

In [84]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
b = np.arange(16)

In [91]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
a = np.arange(16).reshape(4,4)

In [96]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
c = a

In [98]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
c.shape = (4, 4)

In [102]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [104]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
c = a.copy()

In [106]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
c.shape = (2,8)

In [109]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [110]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
c.shape = (4, 4)

In [112]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
# vectorization (multiplication of arrays made cleaner with numpy)
a * c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [118]:
# broadcasting (multiplication of 2 arrays with different dimension)
b = np.arange(4)
b

array([0, 1, 2, 3])

In [119]:
a+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [120]:
a*b

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45]])

In [130]:
a = np.arange(6).reshape(3,1,2)

In [131]:
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [132]:
b = np.arange(6).reshape(3,2,1)

In [135]:
b

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [136]:
a+b

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [137]:
a.dtype

dtype('int64')

In [139]:
a = np.array([(1, "First", 0.2, 1+2j), (2, "Second", 0.4, 1-2j), (1, "Third", 0.6, 1+3j)])

In [140]:
a

array([['1', 'First', '0.2', '(1+2j)'],
       ['2', 'Second', '0.4', '(1-2j)'],
       ['1', 'Third', '0.6', '(1+3j)']], dtype='<U21')

In [143]:
a = np.array([(1, "First", 0.2, 1+2j), (2, "Second", 0.4, 1-2j), (1, "Third", 0.6, 1+3j)], dtype=('i2,a6,f4,c8'))

In [144]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (1, b'Third', 0.6, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [145]:
a[0]

(1, b'First', 0.2, 1.+2.j)

In [146]:
a[1]

(2, b'Second', 0.4, 1.-2.j)

In [147]:
a[2]

(1, b'Third', 0.6, 1.+3.j)

In [150]:
a['f0']

array([1, 2, 1], dtype=int16)

In [151]:
a['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [152]:
a['f2']

array([0.2, 0.4, 0.6], dtype=float32)

In [153]:
a['f3']

array([1.+2.j, 1.-2.j, 1.+3.j], dtype=complex64)

In [155]:
a = np.array([(1, "First", 0.2, 1+2j), (2, "Second", 0.4, 1-2j), (1, "Third", 0.6, 1+3j)], dtype = [('id', 'i2'),('position','a6'),('value','f4'),('complex','c8')])

In [156]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (1, b'Third', 0.6, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [157]:
a['id']

array([1, 2, 1], dtype=int16)

In [159]:
a['position']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [163]:
a.dtype.names = ('idx', 'order', 'value','complex')

In [164]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (1, b'Third', 0.6, 1.+3.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [160]:
np.save('saved_data', a)

In [161]:
data = np.load('saved_data.npy')

In [162]:
data

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (1, b'Third', 0.6, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [172]:
data = np.genfromtxt('01_data.csv', delimiter = ',', names = True)

ValueError: Some errors were detected !
    Line #2 (got 13 columns instead of 12)
    Line #3 (got 13 columns instead of 12)
    Line #4 (got 13 columns instead of 12)
    Line #5 (got 13 columns instead of 12)
    Line #6 (got 13 columns instead of 12)
    Line #7 (got 13 columns instead of 12)
    Line #8 (got 13 columns instead of 12)
    Line #9 (got 13 columns instead of 12)
    Line #10 (got 13 columns instead of 12)
    Line #11 (got 13 columns instead of 12)
    Line #12 (got 13 columns instead of 12)
    Line #13 (got 13 columns instead of 12)
    Line #14 (got 13 columns instead of 12)
    Line #15 (got 13 columns instead of 12)
    Line #16 (got 13 columns instead of 12)
    Line #17 (got 13 columns instead of 12)
    Line #18 (got 13 columns instead of 12)
    Line #19 (got 13 columns instead of 12)
    Line #20 (got 13 columns instead of 12)
    Line #21 (got 13 columns instead of 12)
    Line #22 (got 13 columns instead of 12)
    Line #23 (got 13 columns instead of 12)
    Line #24 (got 13 columns instead of 12)
    Line #25 (got 13 columns instead of 12)
    Line #26 (got 13 columns instead of 12)
    Line #27 (got 13 columns instead of 12)
    Line #28 (got 13 columns instead of 12)
    Line #29 (got 13 columns instead of 12)
    Line #30 (got 13 columns instead of 12)
    Line #31 (got 13 columns instead of 12)
    Line #32 (got 13 columns instead of 12)
    Line #33 (got 13 columns instead of 12)
    Line #34 (got 13 columns instead of 12)
    Line #35 (got 13 columns instead of 12)
    Line #36 (got 13 columns instead of 12)
    Line #37 (got 13 columns instead of 12)
    Line #38 (got 13 columns instead of 12)
    Line #39 (got 13 columns instead of 12)
    Line #40 (got 13 columns instead of 12)
    Line #41 (got 13 columns instead of 12)
    Line #42 (got 13 columns instead of 12)
    Line #43 (got 13 columns instead of 12)
    Line #44 (got 13 columns instead of 12)
    Line #45 (got 13 columns instead of 12)
    Line #46 (got 13 columns instead of 12)
    Line #47 (got 13 columns instead of 12)
    Line #48 (got 13 columns instead of 12)
    Line #49 (got 13 columns instead of 12)
    Line #50 (got 13 columns instead of 12)
    Line #51 (got 13 columns instead of 12)
    Line #52 (got 13 columns instead of 12)
    Line #53 (got 13 columns instead of 12)
    Line #54 (got 13 columns instead of 12)
    Line #55 (got 13 columns instead of 12)
    Line #56 (got 13 columns instead of 12)
    Line #57 (got 13 columns instead of 12)
    Line #58 (got 13 columns instead of 12)
    Line #59 (got 13 columns instead of 12)
    Line #60 (got 13 columns instead of 12)
    Line #61 (got 13 columns instead of 12)
    Line #62 (got 13 columns instead of 12)
    Line #63 (got 13 columns instead of 12)
    Line #64 (got 13 columns instead of 12)
    Line #65 (got 13 columns instead of 12)
    Line #66 (got 13 columns instead of 12)
    Line #67 (got 13 columns instead of 12)
    Line #68 (got 13 columns instead of 12)
    Line #69 (got 13 columns instead of 12)
    Line #70 (got 13 columns instead of 12)
    Line #71 (got 13 columns instead of 12)
    Line #72 (got 13 columns instead of 12)
    Line #73 (got 13 columns instead of 12)
    Line #74 (got 13 columns instead of 12)
    Line #75 (got 13 columns instead of 12)
    Line #76 (got 13 columns instead of 12)
    Line #77 (got 13 columns instead of 12)
    Line #78 (got 13 columns instead of 12)
    Line #79 (got 13 columns instead of 12)
    Line #80 (got 13 columns instead of 12)
    Line #81 (got 13 columns instead of 12)
    Line #82 (got 13 columns instead of 12)
    Line #83 (got 13 columns instead of 12)
    Line #84 (got 13 columns instead of 12)
    Line #85 (got 13 columns instead of 12)
    Line #86 (got 13 columns instead of 12)
    Line #87 (got 13 columns instead of 12)
    Line #88 (got 13 columns instead of 12)
    Line #89 (got 13 columns instead of 12)
    Line #90 (got 13 columns instead of 12)
    Line #91 (got 13 columns instead of 12)
    Line #92 (got 13 columns instead of 12)
    Line #93 (got 13 columns instead of 12)
    Line #94 (got 13 columns instead of 12)
    Line #95 (got 13 columns instead of 12)
    Line #96 (got 13 columns instead of 12)
    Line #97 (got 13 columns instead of 12)
    Line #98 (got 13 columns instead of 12)
    Line #99 (got 13 columns instead of 12)
    Line #100 (got 13 columns instead of 12)
    Line #101 (got 13 columns instead of 12)
    Line #102 (got 13 columns instead of 12)
    Line #103 (got 13 columns instead of 12)
    Line #104 (got 13 columns instead of 12)
    Line #105 (got 13 columns instead of 12)
    Line #106 (got 13 columns instead of 12)
    Line #107 (got 13 columns instead of 12)
    Line #108 (got 13 columns instead of 12)
    Line #109 (got 13 columns instead of 12)
    Line #110 (got 13 columns instead of 12)
    Line #111 (got 13 columns instead of 12)
    Line #112 (got 13 columns instead of 12)
    Line #113 (got 13 columns instead of 12)
    Line #114 (got 13 columns instead of 12)
    Line #115 (got 13 columns instead of 12)
    Line #116 (got 13 columns instead of 12)
    Line #117 (got 13 columns instead of 12)
    Line #118 (got 13 columns instead of 12)
    Line #119 (got 13 columns instead of 12)
    Line #120 (got 13 columns instead of 12)
    Line #121 (got 13 columns instead of 12)
    Line #122 (got 13 columns instead of 12)
    Line #123 (got 13 columns instead of 12)
    Line #124 (got 13 columns instead of 12)
    Line #125 (got 13 columns instead of 12)
    Line #126 (got 13 columns instead of 12)
    Line #127 (got 13 columns instead of 12)
    Line #128 (got 13 columns instead of 12)
    Line #129 (got 13 columns instead of 12)
    Line #130 (got 13 columns instead of 12)
    Line #131 (got 13 columns instead of 12)
    Line #132 (got 13 columns instead of 12)
    Line #133 (got 13 columns instead of 12)
    Line #134 (got 13 columns instead of 12)
    Line #135 (got 13 columns instead of 12)
    Line #136 (got 13 columns instead of 12)
    Line #137 (got 13 columns instead of 12)
    Line #138 (got 13 columns instead of 12)
    Line #139 (got 13 columns instead of 12)
    Line #140 (got 13 columns instead of 12)
    Line #141 (got 13 columns instead of 12)
    Line #142 (got 13 columns instead of 12)
    Line #143 (got 13 columns instead of 12)
    Line #144 (got 13 columns instead of 12)
    Line #145 (got 13 columns instead of 12)
    Line #146 (got 13 columns instead of 12)
    Line #147 (got 13 columns instead of 12)
    Line #148 (got 13 columns instead of 12)
    Line #149 (got 13 columns instead of 12)
    Line #150 (got 13 columns instead of 12)
    Line #151 (got 13 columns instead of 12)
    Line #152 (got 13 columns instead of 12)
    Line #153 (got 13 columns instead of 12)
    Line #154 (got 13 columns instead of 12)
    Line #155 (got 13 columns instead of 12)
    Line #156 (got 13 columns instead of 12)
    Line #157 (got 13 columns instead of 12)
    Line #158 (got 13 columns instead of 12)
    Line #159 (got 13 columns instead of 12)
    Line #160 (got 13 columns instead of 12)
    Line #161 (got 13 columns instead of 12)
    Line #162 (got 13 columns instead of 12)
    Line #163 (got 13 columns instead of 12)
    Line #164 (got 13 columns instead of 12)
    Line #165 (got 13 columns instead of 12)
    Line #166 (got 13 columns instead of 12)
    Line #167 (got 13 columns instead of 12)
    Line #168 (got 13 columns instead of 12)
    Line #169 (got 13 columns instead of 12)
    Line #170 (got 13 columns instead of 12)
    Line #171 (got 13 columns instead of 12)
    Line #172 (got 13 columns instead of 12)
    Line #173 (got 13 columns instead of 12)
    Line #174 (got 13 columns instead of 12)
    Line #175 (got 13 columns instead of 12)
    Line #176 (got 13 columns instead of 12)
    Line #177 (got 13 columns instead of 12)
    Line #178 (got 13 columns instead of 12)
    Line #179 (got 13 columns instead of 12)
    Line #180 (got 13 columns instead of 12)
    Line #181 (got 13 columns instead of 12)
    Line #182 (got 13 columns instead of 12)
    Line #183 (got 13 columns instead of 12)
    Line #184 (got 13 columns instead of 12)
    Line #185 (got 13 columns instead of 12)
    Line #186 (got 13 columns instead of 12)
    Line #187 (got 13 columns instead of 12)
    Line #188 (got 13 columns instead of 12)
    Line #189 (got 13 columns instead of 12)
    Line #190 (got 13 columns instead of 12)
    Line #191 (got 13 columns instead of 12)
    Line #192 (got 13 columns instead of 12)
    Line #193 (got 13 columns instead of 12)
    Line #194 (got 13 columns instead of 12)
    Line #195 (got 13 columns instead of 12)
    Line #196 (got 13 columns instead of 12)
    Line #197 (got 13 columns instead of 12)
    Line #198 (got 13 columns instead of 12)
    Line #199 (got 13 columns instead of 12)
    Line #200 (got 13 columns instead of 12)
    Line #201 (got 13 columns instead of 12)
    Line #202 (got 13 columns instead of 12)
    Line #203 (got 13 columns instead of 12)
    Line #204 (got 13 columns instead of 12)
    Line #205 (got 13 columns instead of 12)
    Line #206 (got 13 columns instead of 12)
    Line #207 (got 13 columns instead of 12)
    Line #208 (got 13 columns instead of 12)
    Line #209 (got 13 columns instead of 12)
    Line #210 (got 13 columns instead of 12)
    Line #211 (got 13 columns instead of 12)
    Line #212 (got 13 columns instead of 12)
    Line #213 (got 13 columns instead of 12)
    Line #214 (got 13 columns instead of 12)
    Line #215 (got 13 columns instead of 12)
    Line #216 (got 13 columns instead of 12)
    Line #217 (got 13 columns instead of 12)
    Line #218 (got 13 columns instead of 12)
    Line #219 (got 13 columns instead of 12)
    Line #220 (got 13 columns instead of 12)
    Line #221 (got 13 columns instead of 12)
    Line #222 (got 13 columns instead of 12)
    Line #223 (got 13 columns instead of 12)
    Line #224 (got 13 columns instead of 12)
    Line #225 (got 13 columns instead of 12)
    Line #226 (got 13 columns instead of 12)
    Line #227 (got 13 columns instead of 12)
    Line #228 (got 13 columns instead of 12)
    Line #229 (got 13 columns instead of 12)
    Line #230 (got 13 columns instead of 12)
    Line #231 (got 13 columns instead of 12)
    Line #232 (got 13 columns instead of 12)
    Line #233 (got 13 columns instead of 12)
    Line #234 (got 13 columns instead of 12)
    Line #235 (got 13 columns instead of 12)
    Line #236 (got 13 columns instead of 12)
    Line #237 (got 13 columns instead of 12)
    Line #238 (got 13 columns instead of 12)
    Line #239 (got 13 columns instead of 12)
    Line #240 (got 13 columns instead of 12)
    Line #241 (got 13 columns instead of 12)
    Line #242 (got 13 columns instead of 12)
    Line #243 (got 13 columns instead of 12)
    Line #244 (got 13 columns instead of 12)
    Line #245 (got 13 columns instead of 12)
    Line #246 (got 13 columns instead of 12)
    Line #247 (got 13 columns instead of 12)
    Line #248 (got 13 columns instead of 12)
    Line #249 (got 13 columns instead of 12)
    Line #250 (got 13 columns instead of 12)
    Line #251 (got 13 columns instead of 12)
    Line #252 (got 13 columns instead of 12)
    Line #253 (got 13 columns instead of 12)
    Line #254 (got 13 columns instead of 12)
    Line #255 (got 13 columns instead of 12)
    Line #256 (got 13 columns instead of 12)
    Line #257 (got 13 columns instead of 12)
    Line #258 (got 13 columns instead of 12)
    Line #259 (got 13 columns instead of 12)
    Line #260 (got 13 columns instead of 12)
    Line #261 (got 13 columns instead of 12)
    Line #262 (got 13 columns instead of 12)
    Line #263 (got 13 columns instead of 12)
    Line #264 (got 13 columns instead of 12)
    Line #265 (got 13 columns instead of 12)
    Line #266 (got 13 columns instead of 12)
    Line #267 (got 13 columns instead of 12)
    Line #268 (got 13 columns instead of 12)
    Line #269 (got 13 columns instead of 12)
    Line #270 (got 13 columns instead of 12)
    Line #271 (got 13 columns instead of 12)
    Line #272 (got 13 columns instead of 12)
    Line #273 (got 13 columns instead of 12)
    Line #274 (got 13 columns instead of 12)
    Line #275 (got 13 columns instead of 12)
    Line #276 (got 13 columns instead of 12)
    Line #277 (got 13 columns instead of 12)
    Line #278 (got 13 columns instead of 12)
    Line #279 (got 13 columns instead of 12)
    Line #280 (got 13 columns instead of 12)
    Line #281 (got 13 columns instead of 12)
    Line #282 (got 13 columns instead of 12)
    Line #283 (got 13 columns instead of 12)
    Line #284 (got 13 columns instead of 12)
    Line #285 (got 13 columns instead of 12)
    Line #286 (got 13 columns instead of 12)
    Line #287 (got 13 columns instead of 12)
    Line #288 (got 13 columns instead of 12)
    Line #289 (got 13 columns instead of 12)
    Line #290 (got 13 columns instead of 12)
    Line #291 (got 13 columns instead of 12)
    Line #292 (got 13 columns instead of 12)
    Line #293 (got 13 columns instead of 12)
    Line #294 (got 13 columns instead of 12)
    Line #295 (got 13 columns instead of 12)
    Line #296 (got 13 columns instead of 12)
    Line #297 (got 13 columns instead of 12)
    Line #298 (got 13 columns instead of 12)
    Line #299 (got 13 columns instead of 12)
    Line #300 (got 13 columns instead of 12)
    Line #301 (got 13 columns instead of 12)
    Line #302 (got 13 columns instead of 12)
    Line #303 (got 13 columns instead of 12)
    Line #304 (got 13 columns instead of 12)
    Line #305 (got 13 columns instead of 12)
    Line #306 (got 13 columns instead of 12)
    Line #307 (got 13 columns instead of 12)
    Line #308 (got 13 columns instead of 12)
    Line #309 (got 13 columns instead of 12)
    Line #310 (got 13 columns instead of 12)
    Line #311 (got 13 columns instead of 12)
    Line #312 (got 13 columns instead of 12)
    Line #313 (got 13 columns instead of 12)
    Line #314 (got 13 columns instead of 12)
    Line #315 (got 13 columns instead of 12)
    Line #316 (got 13 columns instead of 12)
    Line #317 (got 13 columns instead of 12)
    Line #318 (got 13 columns instead of 12)
    Line #319 (got 13 columns instead of 12)
    Line #320 (got 13 columns instead of 12)
    Line #321 (got 13 columns instead of 12)
    Line #322 (got 13 columns instead of 12)
    Line #323 (got 13 columns instead of 12)
    Line #324 (got 13 columns instead of 12)
    Line #325 (got 13 columns instead of 12)
    Line #326 (got 13 columns instead of 12)
    Line #327 (got 13 columns instead of 12)
    Line #328 (got 13 columns instead of 12)
    Line #329 (got 13 columns instead of 12)
    Line #330 (got 13 columns instead of 12)
    Line #331 (got 13 columns instead of 12)
    Line #332 (got 13 columns instead of 12)
    Line #333 (got 13 columns instead of 12)
    Line #334 (got 13 columns instead of 12)
    Line #335 (got 13 columns instead of 12)
    Line #336 (got 13 columns instead of 12)
    Line #337 (got 13 columns instead of 12)
    Line #338 (got 13 columns instead of 12)
    Line #339 (got 13 columns instead of 12)
    Line #340 (got 13 columns instead of 12)
    Line #341 (got 13 columns instead of 12)
    Line #342 (got 13 columns instead of 12)
    Line #343 (got 13 columns instead of 12)
    Line #344 (got 13 columns instead of 12)
    Line #345 (got 13 columns instead of 12)
    Line #346 (got 13 columns instead of 12)
    Line #347 (got 13 columns instead of 12)
    Line #348 (got 13 columns instead of 12)
    Line #349 (got 13 columns instead of 12)
    Line #350 (got 13 columns instead of 12)
    Line #351 (got 13 columns instead of 12)
    Line #352 (got 13 columns instead of 12)
    Line #353 (got 13 columns instead of 12)
    Line #354 (got 13 columns instead of 12)
    Line #355 (got 13 columns instead of 12)
    Line #356 (got 13 columns instead of 12)
    Line #357 (got 13 columns instead of 12)
    Line #358 (got 13 columns instead of 12)
    Line #359 (got 13 columns instead of 12)
    Line #360 (got 13 columns instead of 12)
    Line #361 (got 13 columns instead of 12)
    Line #362 (got 13 columns instead of 12)
    Line #363 (got 13 columns instead of 12)
    Line #364 (got 13 columns instead of 12)
    Line #365 (got 13 columns instead of 12)
    Line #366 (got 13 columns instead of 12)
    Line #367 (got 13 columns instead of 12)
    Line #368 (got 13 columns instead of 12)
    Line #369 (got 13 columns instead of 12)
    Line #370 (got 13 columns instead of 12)
    Line #371 (got 13 columns instead of 12)
    Line #372 (got 13 columns instead of 12)
    Line #373 (got 13 columns instead of 12)
    Line #374 (got 13 columns instead of 12)
    Line #375 (got 13 columns instead of 12)
    Line #376 (got 13 columns instead of 12)
    Line #377 (got 13 columns instead of 12)
    Line #378 (got 13 columns instead of 12)
    Line #379 (got 13 columns instead of 12)
    Line #380 (got 13 columns instead of 12)
    Line #381 (got 13 columns instead of 12)
    Line #382 (got 13 columns instead of 12)
    Line #383 (got 13 columns instead of 12)
    Line #384 (got 13 columns instead of 12)
    Line #385 (got 13 columns instead of 12)
    Line #386 (got 13 columns instead of 12)
    Line #387 (got 13 columns instead of 12)
    Line #388 (got 13 columns instead of 12)
    Line #389 (got 13 columns instead of 12)
    Line #390 (got 13 columns instead of 12)
    Line #391 (got 13 columns instead of 12)
    Line #392 (got 13 columns instead of 12)
    Line #393 (got 13 columns instead of 12)
    Line #394 (got 13 columns instead of 12)
    Line #395 (got 13 columns instead of 12)
    Line #396 (got 13 columns instead of 12)
    Line #397 (got 13 columns instead of 12)
    Line #398 (got 13 columns instead of 12)
    Line #399 (got 13 columns instead of 12)
    Line #400 (got 13 columns instead of 12)
    Line #401 (got 13 columns instead of 12)
    Line #402 (got 13 columns instead of 12)
    Line #403 (got 13 columns instead of 12)
    Line #404 (got 13 columns instead of 12)
    Line #405 (got 13 columns instead of 12)
    Line #406 (got 13 columns instead of 12)
    Line #407 (got 13 columns instead of 12)
    Line #408 (got 13 columns instead of 12)
    Line #409 (got 13 columns instead of 12)
    Line #410 (got 13 columns instead of 12)
    Line #411 (got 13 columns instead of 12)
    Line #412 (got 13 columns instead of 12)
    Line #413 (got 13 columns instead of 12)
    Line #414 (got 13 columns instead of 12)
    Line #415 (got 13 columns instead of 12)
    Line #416 (got 13 columns instead of 12)
    Line #417 (got 13 columns instead of 12)
    Line #418 (got 13 columns instead of 12)
    Line #419 (got 13 columns instead of 12)
    Line #420 (got 13 columns instead of 12)
    Line #421 (got 13 columns instead of 12)
    Line #422 (got 13 columns instead of 12)
    Line #423 (got 13 columns instead of 12)
    Line #424 (got 13 columns instead of 12)
    Line #425 (got 13 columns instead of 12)
    Line #426 (got 13 columns instead of 12)
    Line #427 (got 13 columns instead of 12)
    Line #428 (got 13 columns instead of 12)
    Line #429 (got 13 columns instead of 12)
    Line #430 (got 13 columns instead of 12)
    Line #431 (got 13 columns instead of 12)
    Line #432 (got 13 columns instead of 12)
    Line #433 (got 13 columns instead of 12)
    Line #434 (got 13 columns instead of 12)
    Line #435 (got 13 columns instead of 12)
    Line #436 (got 13 columns instead of 12)
    Line #437 (got 13 columns instead of 12)
    Line #438 (got 13 columns instead of 12)
    Line #439 (got 13 columns instead of 12)
    Line #440 (got 13 columns instead of 12)
    Line #441 (got 13 columns instead of 12)
    Line #442 (got 13 columns instead of 12)
    Line #443 (got 13 columns instead of 12)
    Line #444 (got 13 columns instead of 12)
    Line #445 (got 13 columns instead of 12)
    Line #446 (got 13 columns instead of 12)
    Line #447 (got 13 columns instead of 12)
    Line #448 (got 13 columns instead of 12)
    Line #449 (got 13 columns instead of 12)
    Line #450 (got 13 columns instead of 12)
    Line #451 (got 13 columns instead of 12)
    Line #452 (got 13 columns instead of 12)
    Line #453 (got 13 columns instead of 12)
    Line #454 (got 13 columns instead of 12)
    Line #455 (got 13 columns instead of 12)
    Line #456 (got 13 columns instead of 12)
    Line #457 (got 13 columns instead of 12)
    Line #458 (got 13 columns instead of 12)
    Line #459 (got 13 columns instead of 12)
    Line #460 (got 13 columns instead of 12)
    Line #461 (got 13 columns instead of 12)
    Line #462 (got 13 columns instead of 12)
    Line #463 (got 13 columns instead of 12)
    Line #464 (got 13 columns instead of 12)
    Line #465 (got 13 columns instead of 12)
    Line #466 (got 13 columns instead of 12)
    Line #467 (got 13 columns instead of 12)
    Line #468 (got 13 columns instead of 12)
    Line #469 (got 13 columns instead of 12)
    Line #470 (got 13 columns instead of 12)
    Line #471 (got 13 columns instead of 12)
    Line #472 (got 13 columns instead of 12)
    Line #473 (got 13 columns instead of 12)
    Line #474 (got 13 columns instead of 12)
    Line #475 (got 13 columns instead of 12)
    Line #476 (got 13 columns instead of 12)
    Line #477 (got 13 columns instead of 12)
    Line #478 (got 13 columns instead of 12)
    Line #479 (got 13 columns instead of 12)
    Line #480 (got 13 columns instead of 12)
    Line #481 (got 13 columns instead of 12)
    Line #482 (got 13 columns instead of 12)
    Line #483 (got 13 columns instead of 12)
    Line #484 (got 13 columns instead of 12)
    Line #485 (got 13 columns instead of 12)
    Line #486 (got 13 columns instead of 12)
    Line #487 (got 13 columns instead of 12)
    Line #488 (got 13 columns instead of 12)
    Line #489 (got 13 columns instead of 12)
    Line #490 (got 13 columns instead of 12)
    Line #491 (got 13 columns instead of 12)
    Line #492 (got 13 columns instead of 12)
    Line #493 (got 13 columns instead of 12)
    Line #494 (got 13 columns instead of 12)
    Line #495 (got 13 columns instead of 12)
    Line #496 (got 13 columns instead of 12)
    Line #497 (got 13 columns instead of 12)
    Line #498 (got 13 columns instead of 12)
    Line #499 (got 13 columns instead of 12)
    Line #500 (got 13 columns instead of 12)
    Line #501 (got 13 columns instead of 12)
    Line #502 (got 13 columns instead of 12)
    Line #503 (got 13 columns instead of 12)
    Line #504 (got 13 columns instead of 12)
    Line #505 (got 13 columns instead of 12)
    Line #506 (got 13 columns instead of 12)
    Line #507 (got 13 columns instead of 12)
    Line #508 (got 13 columns instead of 12)
    Line #509 (got 13 columns instead of 12)
    Line #510 (got 13 columns instead of 12)
    Line #511 (got 13 columns instead of 12)
    Line #512 (got 13 columns instead of 12)
    Line #513 (got 13 columns instead of 12)
    Line #514 (got 13 columns instead of 12)
    Line #515 (got 13 columns instead of 12)
    Line #516 (got 13 columns instead of 12)
    Line #517 (got 13 columns instead of 12)
    Line #518 (got 13 columns instead of 12)
    Line #519 (got 13 columns instead of 12)
    Line #520 (got 13 columns instead of 12)
    Line #521 (got 13 columns instead of 12)
    Line #522 (got 13 columns instead of 12)
    Line #523 (got 13 columns instead of 12)
    Line #524 (got 13 columns instead of 12)
    Line #525 (got 13 columns instead of 12)
    Line #526 (got 13 columns instead of 12)
    Line #527 (got 13 columns instead of 12)
    Line #528 (got 13 columns instead of 12)
    Line #529 (got 13 columns instead of 12)
    Line #530 (got 13 columns instead of 12)
    Line #531 (got 13 columns instead of 12)
    Line #532 (got 13 columns instead of 12)
    Line #533 (got 13 columns instead of 12)
    Line #534 (got 13 columns instead of 12)
    Line #535 (got 13 columns instead of 12)
    Line #536 (got 13 columns instead of 12)
    Line #537 (got 13 columns instead of 12)
    Line #538 (got 13 columns instead of 12)
    Line #539 (got 13 columns instead of 12)
    Line #540 (got 13 columns instead of 12)
    Line #541 (got 13 columns instead of 12)
    Line #542 (got 13 columns instead of 12)
    Line #543 (got 13 columns instead of 12)
    Line #544 (got 13 columns instead of 12)
    Line #545 (got 13 columns instead of 12)
    Line #546 (got 13 columns instead of 12)
    Line #547 (got 13 columns instead of 12)
    Line #548 (got 13 columns instead of 12)
    Line #549 (got 13 columns instead of 12)
    Line #550 (got 13 columns instead of 12)
    Line #551 (got 13 columns instead of 12)
    Line #552 (got 13 columns instead of 12)
    Line #553 (got 13 columns instead of 12)
    Line #554 (got 13 columns instead of 12)
    Line #555 (got 13 columns instead of 12)
    Line #556 (got 13 columns instead of 12)
    Line #557 (got 13 columns instead of 12)
    Line #558 (got 13 columns instead of 12)
    Line #559 (got 13 columns instead of 12)
    Line #560 (got 13 columns instead of 12)
    Line #561 (got 13 columns instead of 12)
    Line #562 (got 13 columns instead of 12)
    Line #563 (got 13 columns instead of 12)
    Line #564 (got 13 columns instead of 12)
    Line #565 (got 13 columns instead of 12)
    Line #566 (got 13 columns instead of 12)
    Line #567 (got 13 columns instead of 12)
    Line #568 (got 13 columns instead of 12)
    Line #569 (got 13 columns instead of 12)
    Line #570 (got 13 columns instead of 12)
    Line #571 (got 13 columns instead of 12)
    Line #572 (got 13 columns instead of 12)
    Line #573 (got 13 columns instead of 12)
    Line #574 (got 13 columns instead of 12)
    Line #575 (got 13 columns instead of 12)
    Line #576 (got 13 columns instead of 12)
    Line #577 (got 13 columns instead of 12)
    Line #578 (got 13 columns instead of 12)
    Line #579 (got 13 columns instead of 12)
    Line #580 (got 13 columns instead of 12)
    Line #581 (got 13 columns instead of 12)
    Line #582 (got 13 columns instead of 12)
    Line #583 (got 13 columns instead of 12)
    Line #584 (got 13 columns instead of 12)
    Line #585 (got 13 columns instead of 12)
    Line #586 (got 13 columns instead of 12)
    Line #587 (got 13 columns instead of 12)
    Line #588 (got 13 columns instead of 12)
    Line #589 (got 13 columns instead of 12)
    Line #590 (got 13 columns instead of 12)
    Line #591 (got 13 columns instead of 12)
    Line #592 (got 13 columns instead of 12)
    Line #593 (got 13 columns instead of 12)
    Line #594 (got 13 columns instead of 12)
    Line #595 (got 13 columns instead of 12)
    Line #596 (got 13 columns instead of 12)
    Line #597 (got 13 columns instead of 12)
    Line #598 (got 13 columns instead of 12)
    Line #599 (got 13 columns instead of 12)
    Line #600 (got 13 columns instead of 12)
    Line #601 (got 13 columns instead of 12)
    Line #602 (got 13 columns instead of 12)
    Line #603 (got 13 columns instead of 12)
    Line #604 (got 13 columns instead of 12)
    Line #605 (got 13 columns instead of 12)
    Line #606 (got 13 columns instead of 12)
    Line #607 (got 13 columns instead of 12)
    Line #608 (got 13 columns instead of 12)
    Line #609 (got 13 columns instead of 12)
    Line #610 (got 13 columns instead of 12)
    Line #611 (got 13 columns instead of 12)
    Line #612 (got 13 columns instead of 12)
    Line #613 (got 13 columns instead of 12)
    Line #614 (got 13 columns instead of 12)
    Line #615 (got 13 columns instead of 12)
    Line #616 (got 13 columns instead of 12)
    Line #617 (got 13 columns instead of 12)
    Line #618 (got 13 columns instead of 12)
    Line #619 (got 13 columns instead of 12)
    Line #620 (got 13 columns instead of 12)
    Line #621 (got 13 columns instead of 12)
    Line #622 (got 13 columns instead of 12)
    Line #623 (got 13 columns instead of 12)
    Line #624 (got 13 columns instead of 12)
    Line #625 (got 13 columns instead of 12)
    Line #626 (got 13 columns instead of 12)
    Line #627 (got 13 columns instead of 12)
    Line #628 (got 13 columns instead of 12)
    Line #629 (got 13 columns instead of 12)
    Line #630 (got 13 columns instead of 12)
    Line #631 (got 13 columns instead of 12)
    Line #632 (got 13 columns instead of 12)
    Line #633 (got 13 columns instead of 12)
    Line #634 (got 13 columns instead of 12)
    Line #635 (got 13 columns instead of 12)
    Line #636 (got 13 columns instead of 12)
    Line #637 (got 13 columns instead of 12)
    Line #638 (got 13 columns instead of 12)
    Line #639 (got 13 columns instead of 12)
    Line #640 (got 13 columns instead of 12)
    Line #641 (got 13 columns instead of 12)
    Line #642 (got 13 columns instead of 12)
    Line #643 (got 13 columns instead of 12)
    Line #644 (got 13 columns instead of 12)
    Line #645 (got 13 columns instead of 12)
    Line #646 (got 13 columns instead of 12)
    Line #647 (got 13 columns instead of 12)
    Line #648 (got 13 columns instead of 12)
    Line #649 (got 13 columns instead of 12)
    Line #650 (got 13 columns instead of 12)
    Line #651 (got 13 columns instead of 12)
    Line #652 (got 13 columns instead of 12)
    Line #653 (got 13 columns instead of 12)
    Line #654 (got 13 columns instead of 12)
    Line #655 (got 13 columns instead of 12)
    Line #656 (got 13 columns instead of 12)
    Line #657 (got 13 columns instead of 12)
    Line #658 (got 13 columns instead of 12)
    Line #659 (got 13 columns instead of 12)
    Line #660 (got 13 columns instead of 12)
    Line #661 (got 13 columns instead of 12)
    Line #662 (got 13 columns instead of 12)
    Line #663 (got 13 columns instead of 12)
    Line #664 (got 13 columns instead of 12)
    Line #665 (got 13 columns instead of 12)
    Line #666 (got 13 columns instead of 12)
    Line #667 (got 13 columns instead of 12)
    Line #668 (got 13 columns instead of 12)
    Line #669 (got 13 columns instead of 12)
    Line #670 (got 13 columns instead of 12)
    Line #671 (got 13 columns instead of 12)
    Line #672 (got 13 columns instead of 12)
    Line #673 (got 13 columns instead of 12)
    Line #674 (got 13 columns instead of 12)
    Line #675 (got 13 columns instead of 12)
    Line #676 (got 13 columns instead of 12)
    Line #677 (got 13 columns instead of 12)
    Line #678 (got 13 columns instead of 12)
    Line #679 (got 13 columns instead of 12)
    Line #680 (got 13 columns instead of 12)
    Line #681 (got 13 columns instead of 12)
    Line #682 (got 13 columns instead of 12)
    Line #683 (got 13 columns instead of 12)
    Line #684 (got 13 columns instead of 12)
    Line #685 (got 13 columns instead of 12)
    Line #686 (got 13 columns instead of 12)
    Line #687 (got 13 columns instead of 12)
    Line #688 (got 13 columns instead of 12)
    Line #689 (got 13 columns instead of 12)
    Line #690 (got 13 columns instead of 12)
    Line #691 (got 13 columns instead of 12)
    Line #692 (got 13 columns instead of 12)
    Line #693 (got 13 columns instead of 12)
    Line #694 (got 13 columns instead of 12)
    Line #695 (got 13 columns instead of 12)
    Line #696 (got 13 columns instead of 12)
    Line #697 (got 13 columns instead of 12)
    Line #698 (got 13 columns instead of 12)
    Line #699 (got 13 columns instead of 12)
    Line #700 (got 13 columns instead of 12)
    Line #701 (got 13 columns instead of 12)
    Line #702 (got 13 columns instead of 12)
    Line #703 (got 13 columns instead of 12)
    Line #704 (got 13 columns instead of 12)
    Line #705 (got 13 columns instead of 12)
    Line #706 (got 13 columns instead of 12)
    Line #707 (got 13 columns instead of 12)
    Line #708 (got 13 columns instead of 12)
    Line #709 (got 13 columns instead of 12)
    Line #710 (got 13 columns instead of 12)
    Line #711 (got 13 columns instead of 12)
    Line #712 (got 13 columns instead of 12)
    Line #713 (got 13 columns instead of 12)
    Line #714 (got 13 columns instead of 12)
    Line #715 (got 13 columns instead of 12)
    Line #716 (got 13 columns instead of 12)
    Line #717 (got 13 columns instead of 12)
    Line #718 (got 13 columns instead of 12)
    Line #719 (got 13 columns instead of 12)
    Line #720 (got 13 columns instead of 12)
    Line #721 (got 13 columns instead of 12)
    Line #722 (got 13 columns instead of 12)
    Line #723 (got 13 columns instead of 12)
    Line #724 (got 13 columns instead of 12)
    Line #725 (got 13 columns instead of 12)
    Line #726 (got 13 columns instead of 12)
    Line #727 (got 13 columns instead of 12)
    Line #728 (got 13 columns instead of 12)
    Line #729 (got 13 columns instead of 12)
    Line #730 (got 13 columns instead of 12)
    Line #731 (got 13 columns instead of 12)
    Line #732 (got 13 columns instead of 12)
    Line #733 (got 13 columns instead of 12)
    Line #734 (got 13 columns instead of 12)
    Line #735 (got 13 columns instead of 12)
    Line #736 (got 13 columns instead of 12)
    Line #737 (got 13 columns instead of 12)
    Line #738 (got 13 columns instead of 12)
    Line #739 (got 13 columns instead of 12)
    Line #740 (got 13 columns instead of 12)
    Line #741 (got 13 columns instead of 12)
    Line #742 (got 13 columns instead of 12)
    Line #743 (got 13 columns instead of 12)
    Line #744 (got 13 columns instead of 12)
    Line #745 (got 13 columns instead of 12)
    Line #746 (got 13 columns instead of 12)
    Line #747 (got 13 columns instead of 12)
    Line #748 (got 13 columns instead of 12)
    Line #749 (got 13 columns instead of 12)
    Line #750 (got 13 columns instead of 12)
    Line #751 (got 13 columns instead of 12)
    Line #752 (got 13 columns instead of 12)
    Line #753 (got 13 columns instead of 12)
    Line #754 (got 13 columns instead of 12)
    Line #755 (got 13 columns instead of 12)
    Line #756 (got 13 columns instead of 12)
    Line #757 (got 13 columns instead of 12)
    Line #758 (got 13 columns instead of 12)
    Line #759 (got 13 columns instead of 12)
    Line #760 (got 13 columns instead of 12)
    Line #761 (got 13 columns instead of 12)
    Line #762 (got 13 columns instead of 12)
    Line #763 (got 13 columns instead of 12)
    Line #764 (got 13 columns instead of 12)
    Line #765 (got 13 columns instead of 12)
    Line #766 (got 13 columns instead of 12)
    Line #767 (got 13 columns instead of 12)
    Line #768 (got 13 columns instead of 12)
    Line #769 (got 13 columns instead of 12)
    Line #770 (got 13 columns instead of 12)
    Line #771 (got 13 columns instead of 12)
    Line #772 (got 13 columns instead of 12)
    Line #773 (got 13 columns instead of 12)
    Line #774 (got 13 columns instead of 12)
    Line #775 (got 13 columns instead of 12)
    Line #776 (got 13 columns instead of 12)
    Line #777 (got 13 columns instead of 12)
    Line #778 (got 13 columns instead of 12)
    Line #779 (got 13 columns instead of 12)
    Line #780 (got 13 columns instead of 12)
    Line #781 (got 13 columns instead of 12)
    Line #782 (got 13 columns instead of 12)
    Line #783 (got 13 columns instead of 12)
    Line #784 (got 13 columns instead of 12)
    Line #785 (got 13 columns instead of 12)
    Line #786 (got 13 columns instead of 12)
    Line #787 (got 13 columns instead of 12)
    Line #788 (got 13 columns instead of 12)
    Line #789 (got 13 columns instead of 12)
    Line #790 (got 13 columns instead of 12)
    Line #791 (got 13 columns instead of 12)
    Line #792 (got 13 columns instead of 12)
    Line #793 (got 13 columns instead of 12)
    Line #794 (got 13 columns instead of 12)
    Line #795 (got 13 columns instead of 12)
    Line #796 (got 13 columns instead of 12)
    Line #797 (got 13 columns instead of 12)
    Line #798 (got 13 columns instead of 12)
    Line #799 (got 13 columns instead of 12)
    Line #800 (got 13 columns instead of 12)
    Line #801 (got 13 columns instead of 12)
    Line #802 (got 13 columns instead of 12)
    Line #803 (got 13 columns instead of 12)
    Line #804 (got 13 columns instead of 12)
    Line #805 (got 13 columns instead of 12)
    Line #806 (got 13 columns instead of 12)
    Line #807 (got 13 columns instead of 12)
    Line #808 (got 13 columns instead of 12)
    Line #809 (got 13 columns instead of 12)
    Line #810 (got 13 columns instead of 12)
    Line #811 (got 13 columns instead of 12)
    Line #812 (got 13 columns instead of 12)
    Line #813 (got 13 columns instead of 12)
    Line #814 (got 13 columns instead of 12)
    Line #815 (got 13 columns instead of 12)
    Line #816 (got 13 columns instead of 12)
    Line #817 (got 13 columns instead of 12)
    Line #818 (got 13 columns instead of 12)
    Line #819 (got 13 columns instead of 12)
    Line #820 (got 13 columns instead of 12)
    Line #821 (got 13 columns instead of 12)
    Line #822 (got 13 columns instead of 12)
    Line #823 (got 13 columns instead of 12)
    Line #824 (got 13 columns instead of 12)
    Line #825 (got 13 columns instead of 12)
    Line #826 (got 13 columns instead of 12)
    Line #827 (got 13 columns instead of 12)
    Line #828 (got 13 columns instead of 12)
    Line #829 (got 13 columns instead of 12)
    Line #830 (got 13 columns instead of 12)
    Line #831 (got 13 columns instead of 12)
    Line #832 (got 13 columns instead of 12)
    Line #833 (got 13 columns instead of 12)
    Line #834 (got 13 columns instead of 12)
    Line #835 (got 13 columns instead of 12)
    Line #836 (got 13 columns instead of 12)
    Line #837 (got 13 columns instead of 12)
    Line #838 (got 13 columns instead of 12)
    Line #839 (got 13 columns instead of 12)
    Line #840 (got 13 columns instead of 12)
    Line #841 (got 13 columns instead of 12)
    Line #842 (got 13 columns instead of 12)
    Line #843 (got 13 columns instead of 12)
    Line #844 (got 13 columns instead of 12)
    Line #845 (got 13 columns instead of 12)
    Line #846 (got 13 columns instead of 12)
    Line #847 (got 13 columns instead of 12)
    Line #848 (got 13 columns instead of 12)
    Line #849 (got 13 columns instead of 12)
    Line #850 (got 13 columns instead of 12)
    Line #851 (got 13 columns instead of 12)
    Line #852 (got 13 columns instead of 12)
    Line #853 (got 13 columns instead of 12)
    Line #854 (got 13 columns instead of 12)
    Line #855 (got 13 columns instead of 12)
    Line #856 (got 13 columns instead of 12)
    Line #857 (got 13 columns instead of 12)
    Line #858 (got 13 columns instead of 12)
    Line #859 (got 13 columns instead of 12)
    Line #860 (got 13 columns instead of 12)
    Line #861 (got 13 columns instead of 12)
    Line #862 (got 13 columns instead of 12)
    Line #863 (got 13 columns instead of 12)
    Line #864 (got 13 columns instead of 12)
    Line #865 (got 13 columns instead of 12)
    Line #866 (got 13 columns instead of 12)
    Line #867 (got 13 columns instead of 12)
    Line #868 (got 13 columns instead of 12)
    Line #869 (got 13 columns instead of 12)
    Line #870 (got 13 columns instead of 12)
    Line #871 (got 13 columns instead of 12)
    Line #872 (got 13 columns instead of 12)
    Line #873 (got 13 columns instead of 12)
    Line #874 (got 13 columns instead of 12)
    Line #875 (got 13 columns instead of 12)
    Line #876 (got 13 columns instead of 12)
    Line #877 (got 13 columns instead of 12)
    Line #878 (got 13 columns instead of 12)
    Line #879 (got 13 columns instead of 12)
    Line #880 (got 13 columns instead of 12)
    Line #881 (got 13 columns instead of 12)
    Line #882 (got 13 columns instead of 12)
    Line #883 (got 13 columns instead of 12)
    Line #884 (got 13 columns instead of 12)
    Line #885 (got 13 columns instead of 12)
    Line #886 (got 13 columns instead of 12)
    Line #887 (got 13 columns instead of 12)
    Line #888 (got 13 columns instead of 12)
    Line #889 (got 13 columns instead of 12)
    Line #890 (got 13 columns instead of 12)
    Line #891 (got 13 columns instead of 12)
    Line #892 (got 13 columns instead of 12)

In [183]:
data = np.genfromtxt('02_data.csv', delimiter = ',', names = True)

In [184]:
data

array([(1., nan, 123.), (2., nan, 124.)],
      dtype=[('id', '<f8'), ('city', '<f8'), ('loc', '<f8')])

In [185]:
data[1]

(2., nan, 124.)

In [186]:
data[0]

(1., nan, 123.)

In [206]:
a = np.array([(1, "First", 0.2, 1+2j), (2, "Second", 0.4, 1-2j), (1, "Third", 0.6, 1+3j)], dtype=('i2,a8,f4,c8'))

In [207]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (1, b'Third', 0.6, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S8'), ('f2', '<f4'), ('f3', '<c8')])

In [208]:
a[2]

(1, b'Third', 0.6, 1.+3.j)

In [209]:
a['f1']

array([b'First', b'Second', b'Third'], dtype='|S8')

In [210]:
a['f0']

array([1, 2, 1], dtype=int16)

In [212]:
data = np.genfromtxt('02_data.csv', delimiter = ',', names = True)

In [213]:
data

array([(1., nan, 123.), (2., nan, 124.)],
      dtype=[('id', '<f8'), ('city', '<f8'), ('loc', '<f8')])

In [215]:
data[0]

(1., nan, 123.)

In [216]:
data[1]

(2., nan, 124.)

In [217]:
data = np.genfromtxt('02_data.csv', delimiter = ',', names = True, dtype=None)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [218]:
data

array([(1, b'"ktm"', 123), (2, b'"del"', 124)],
      dtype=[('id', '<i8'), ('city', 'S5'), ('loc', '<i8')])